version: 2.1

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.3.0
  virtuajobs: virtuaorbs/jobs@0.1.0

jobs:
  test-job-campaigns:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-test-suites:
          filename: 'test_campaigns'
          suite: 'spec/controllers/campaigns_spec.rb'
  test-job-files:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-test-suites:
          filename: 'test_files'
          suite: 'spec/controllers/files_spec.rb'
  test-job-messages:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-test-suites:
          filename: 'test_messages'
          suite: 'spec/controllers/messages_spec.rb'

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - virtuajobs/rubocop_job_2-6-3
      - test-job-campaigns:
          requires:
            - virtuajobs/rubocop_job_2-6-3
      - test-job-files:
          requires:
            - virtuajobs/rubocop_job_2-6-3
      - test-job-messages:
          requires:
            - virtuajobs/rubocop_job_2-6-3
      - virtuajobs/documentation_job_2-6-3:
          requires:
            - virtuajobs/rubocop_job_2-6-3
      - virtuajobs/deploy_job_2-6-3:
          requires:
            - test-job-campaigns
            - test-job-files
            - test-job-messages
          filters:
            branches:
              only: master