version: 2.1

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.3.0

jobs:
  test-job-campaigns:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-test-suites:
          filename: 'test_campaigns'
          suite: 'spec/controllers/campaigns_spec.rb'
  test-job-files:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-test-suites:
          filename: 'test_files'
          suite: 'spec/controllers/files_spec.rb'
  test-job-messages:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/run-test-suites:
          filename: 'test_messages'
          suite: 'spec/controllers/messages_spec.rb'
  doc-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/generate-documentation

  rubocop-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/perform-rubocop-analysis

  deploy-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/perform-capistrano-command:
          command: "deploy"

  restart-job:
    executor: virtuaexecutors/mongoruby_2-6-3
    steps:
      - virtuacommands/perform-capistrano-command:
          command: "deploy:start"


workflows:
  version: 2.1
  build-deploy:
    jobs:
      - rubocop-job
      - test-job-campaigns:
          requires:
            - rubocop-job
      - test-job-files:
          requires:
            - rubocop-job
      - test-job-messages:
          requires:
            - rubocop-job
      - doc-job:
          requires:
            - rubocop-job
      - deploy-job:
          requires:
            - test-job-campaigns
            - test-job-files
            - test-job-messages
          filters:
            branches:
              only: master
  daily-restart:
    triggers:
      - schedule:
          cron: "5 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - restart-job